### PR TITLE
The Big Hack Job

### PR DESCRIPTION
**Pull request by seanparsons**
This creates 3 projects, argonaut, argonaut-scalaz and argonaut-monocle.

The core argonaut project has no dependencies on Scalaz or Monocle at all, for the moment the 3 projects will be in lock-step but I'm pondering a future where they don't need to be. The main change as a result of that is that there's a move back from \/ to Either.

There's a lot of empty traits/objects in there as a result of me moving things around, I'm tempted to think a few of them would likely end up with stuff in them

Paging @julien-truffaut for his input on the Monocle side of things.

### CODE REVIEW

**Comment by julien-truffaut** [comment]
I will have a look during the weekend but that's seem really good

**Comment by seanparsons** [comment]
@julien-truffaut I'm tempted to think the whole name collision thing isn't a huge deal in the grand scheme of things. Worst case scenario either they have to be excluded from imports or the objects they live on have to be specified as well.

**Comment by julien-truffaut** [comment]
@seanparsons do you mean that they will not be a mega import for `argonaut-monocle`?

**Comment by seanparsons** [comment]
There would be, but within the argonaut-monocle library there aren't collisions are there?

**Comment by julien-truffaut** [comment]
at the moment they are, e.g.:

```scala
val fail: Prism[ACursor, HCursor]
def fail[A]: Prism[DecodeResult[A], (String, CursorHistory)]
```

**Comment by seanparsons** [comment]
My first thought would be to rename them acursorFail and decodeResultFail respectively, but that doesn't hugely fill me with happiness.

**Comment by julien-truffaut** [comment]
@seanparsons I am also not happy about this solution but it is probably the best we have. If we decide to go for it, I would advocate that we make the pattern consistent e.g. `hCursorHistory` instead of `history` and `jsonBool` or `jsonBoolean` instead of `jBoolPrism `

**Comment by seanparsons** [comment]
@julien-truffaut I'm totally down with that, while making a breaking change it's probably worth making this kind of change too.

**Comment by julien-truffaut** [comment]
by the way, I don't know what is your plan in terms of release but in Monocle we are waiting for scalaz 7.2 https://github.com/scalaz/scalaz/issues/1029

**Comment by seanparsons** [comment]
@julien-truffaut It would make sense to line the 6.2 release up with both of those releases.

**Pull request merged**
