### PR TITLE
Added the possibility to create a CodecJson from a String parser and a renderer

### PR DESCRIPTION
**Pull request by etorreborre**
This is particularly useful when string parsers already exist for some data types.

I'm open to name suggestions for the newly introduced functions.

### CODE REVIEW

**Comment by seanparsons** [comment]
Hardest bit of programming is naming things, etc.

I'm currently pondering if this is a more common general pattern, which is why I'm slightly loathe to merge it for the moment. Maybe a little utility method on CodecJson/DecodeJson since contramap suffices on EncodeJson instead?

**Comment by etorreborre** [comment]
Another possibility would be to introduce something called `xmapSafe`:
```
trait CodecJson[A] {
   def xmapSafe[B](parser: A => String \/ B, renderer: B => A): CodecJson[B] = ???
}

CodecJson.derived[String].xmapSafe(parser, renderer)
```

**Comment by xuwei-k** [comment]
https://mpilquist.github.io/blog/2015/06/18/invariant-shadows/

xflatMap ?

**Comment by etorreborre** [comment]
I don't know what is the best signature really for something on `CodecJson` so I dropped that. What I mostly need is `def fromParser[A : DecodeJson, B](parser: A => String \/ B): DecodeJson[B]` (and DecodeResult.fromDisjunction`). 

Then I can build my `Encode/DecodeJson` instances separately using `contramap/flatMap`.

**Comment by etorreborre** [comment]
@seanparsons @xuwei-k I side-stepped the `xFlatMap` question and just left `DecodJson.fromParser` and `DecodeResult.fromDisjunction`. Is that ok?

**Comment by etorreborre** [comment]
Maybe this PR is not such a big win so I am closing it for now.

**Comment by seanparsons** [comment]
@etorreborre I think it's definitely a win, my attention has just been on splitting Argonaut up into smaller libs and other stuff external to the project.

**Comment by etorreborre** [comment]
@seanparsons you can ping me when you're ready to review that again and I'll rebase on the current state of master then.

**Pull request closed without merging**
