### PR TITLE
Preserve order for Json#toString.

### PR DESCRIPTION
**Pull request by kevinmeredith**
Closes https://github.com/argonaut-io/argonaut/issues/138.

### CODE REVIEW

**Comment by kevinmeredith** [comment]
Please take a look at this one when you can, @seanparsons.

**Comment by kevinmeredith** [comment]
Actually, looks like those `import`'s are needed!

I reverted their deletions. Let's see if the build succeeds.

**Comment by kevinmeredith** [comment]
Bump :)

**Comment by seanparsons** [comment]
@kevinmeredith Please don't do that.

**Comment by kevinmeredith** [comment]
OK - understood.

**Comment by kevinmeredith** [comment]
Could you please let me know if PR is OK? I'm grateful for this library's existence, so I'd like to contribute in any way possible! 

Thank you!

**Comment by seanparsons** [comment]
@kevinmeredith Fine by me, apologies, I've been rammed with work in the last couple of weeks.

**Pull request merged**
