### PR TITLE
Add jawn support.

### PR DESCRIPTION
**Pull request by rossabaker**
This is a direct copy of jawn-argonaut's parser and a translation of
its spec into Argonaut's test stack.

See #218, non/jawn#49.

### CODE REVIEW

**Comment by seanparsons** [comment]
@rossabaker Looks like there's a compile error with the tests...

**Comment by rossabaker** [comment]
Urgh.  I was sleepy and missed a `git add` after a final change.  cfe080b should fix it.

**Comment by seanparsons** [comment]
@julien-truffaut Is Monocle being compiled against Java 8? That appears to be the indication from the Travis errors.

**Comment by julien-truffaut** [comment]
no, we started to compile against java 8 yesterday. So it can only be on `1.3.0-SNAPSHOT`

**Comment by julien-truffaut** [comment]
ah but that's the version used in argonaut. I believe we can change the version of monocle to `1.2.0`

**Comment by seanparsons** [comment]
Ah, I was tracking 1.3.0 for the 6.2 release thinking it would be nice to lockstep release it.

**Comment by julien-truffaut** [comment]
There is no plan for `1.3.0` anytime soon, we release `1.2.0` on Dec 17, 2015

**Pull request merged**
