### PR TITLE
add new typeclass EncodeJsonKey

### PR DESCRIPTION
**Pull request by xuwei-k**
generalize IMapEncodeJson and MapLikeEncodeJson

### CODE REVIEW

**Comment by seanparsons** [comment]
I'm guessing this will make things binary incompatible?

**Comment by xuwei-k** [comment]
Yeah, This is not binary incompatible changes.

**Comment by xuwei-k** [comment]
Yeah, This is binary incompatible changes.
We can not add methods to trait when keep binary compatibility.

There is a other way when  keep binary compatibility https://github.com/xuwei-k/argonaut/commit/718324f216c42328caf`

**Comment by seanparsons** [comment]
It was more an observation that it would.

**Pull request merged**
