### PR TITLE
Use applyDynamic in JsonPaths to allow more terse array indexing

### PR DESCRIPTION
**Pull request by paulbrimicombe**
We can use `applyDynamic` to allow simple array indexing. Given the following JSON

```json
{
  "array": [0, 1, 2, 3, 4]
}
```

this change allows us to access an element of `array` like this: `root.array(1)` rather than like this: `root.array.index(1)`

I could only find a relevant test for `JsonPath` and not for `JsonFoldPath` and `JsonTraversalPath` which I found a little worrying. Have I missed something somewhere?

### CODE REVIEW

**Comment by julien-truffaut** [comment]
An issue with `applyDynamic` is that you need the array to be inside of an object but you can't use it on a top level json array which makes the API a bit inconsistent. Why not using a simple `apply` method?

With regards to tests, there are a few unit test using JsonTraversalPath and JsonFoldPath: https://github.com/argonaut-io/argonaut/blob/master/argonaut-monocle/src/test/scala/argonaut/JsonPathSpecification.scala#L56-L78 

but to be honest, it is more a cheap documentation than a real test suite. All the `JsonPath` DSL really rely on the lawfulness of optics which in this case is well tested: https://github.com/argonaut-io/argonaut/blob/master/argonaut-monocle/src/test/scala/argonaut/JsonMonocleSpecification.scala

**Comment by paulbrimicombe** [comment]
If you try using a normal `apply` method you'll find that you can't. Replacing the `applyDynamic` with a normal `apply` method you get:

```
[error]  found   : String("cars")
[error]  required: ?{def apply: ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method augmentString in object Predef of type (x: String)scala.collection.immutable.StringOps
[error]  and method ***If you see this message this means that you've forgotten an operator after the description string: you should write "example" >> result *** in trait BlockDsl of type (s: String)argonaut.JsonPathSpecification.WarningForgottenOperator
```

I think this is because when you call `root.cars(0)` it doesn't call your `selectDynamic` and then `apply` -- it looks for `applyDynamic` instead.

You are completely correct about not being able to reference a specific index on the root path. This could easily be achieved by adding a vanilla `apply` method like this in addition to the `applyDynamic` method:

```
  def apply(i: Int): JsonPath = index(i)
```

Then you can do something like:

```
  root(1).getOption(json)
```

**Comment by paulbrimicombe** [comment]
I've added the normal `apply` method and a test to show how it works.

**Comment by seanparsons** [comment]
@julien-truffaut I'm happy to defer to you on this one.

**Comment by julien-truffaut** [comment]
Awesome. I didn't know that we needed `applyDynamic` because of the interaction with `selectDynamic`.

Thanks @paulbrimicombe

**Pull request merged**
