### PR TITLE
Removed Covariance from DecodeJson

### PR DESCRIPTION
**Pull request by reactormonk**
Not sure how to remove the contravariance from `EncodeJson`.

### CODE REVIEW

**Comment by alexarchambault** [comment]
👍 implicit lookup somehow chokes on contravariance, which makes the derivations of argonaut-shapeless fail with argonaut 6.2.

**Comment by seanparsons** [comment]
@alexarchambault Unless these things are logged as issues, I'm not going to know to fix them!

**Comment by reactormonk** [comment]
@alexarchambault so gotta remove the contravariance too?

**Comment by alexarchambault** [comment]
@reactormonk Yep, like this: https://github.com/alexarchambault/argonaut/commit/65eb2357ede8e6803e1d934bbc3cd61be1b9efdd.

@seanparsons Yep, sorry, I was fine on 6.1, actually! (And was busy on other projects too.)

-> [argonaut-6.2 branch](https://github.com/alexarchambault/argonaut-shapeless/tree/topic/argonaut-6.2) of argonaut-shapeless, which requires dropping both the covariance of `DecodeJson` and the contravariance of `EncodeJson`.

**Comment by tonymorris** [comment]
Always remove variance.

**Comment by reactormonk** [comment]
@alexarchambault Make a PR, so we can get things rolling.

**Comment by alexarchambault** [comment]
Here you go: https://github.com/argonaut-io/argonaut/pull/240

**Pull request merged**
