### PR TITLE
JsonFoldPath and unsafe optics

### PR DESCRIPTION
**Pull request by julien-truffaut**
- add JsonFoldPath and `filter`
- add `unsaferFilter`, `unsafeAs` 
- rename `arrFilter` to `filterByIndex` and `objFilter` to and `filterByField`

I am not sure we want to add `unsaferFilter`, `unsafeAs` as they are unlawful but they are quite convenient. If you prefer I will remove them from the PR.

### CODE REVIEW

**Comment by seanparsons** [comment]
I think I'd prefer to avoid the unsafe cases, just to avoid any shenanigans.

**Comment by julien-truffaut** [comment]
Sure, I will update the PR

**Comment by julien-truffaut** [comment]
updated

**Comment by seanparsons** [comment]
@julien-truffaut Awesomes!

**Pull request merged**
