### PR TITLE
Scalaz 7.2 support for 6.1.x

### PR DESCRIPTION
**Pull request by jvliwanag**
Scalaz 7.2 is currently supported for 6.2-M1. However there's a significant difference between 6.1 and 6.2 such that upgrading isn't trivial. So here's an intermediary step providing 7.2 support for the 6.1 series.

### CODE REVIEW

**Comment by seanparsons** [comment]
I'm not sure this is a good idea going into the 6.1.x series, it's somewhat crossing the streams. As at some random point in time (if I were a random dev using Argonaut) for the 6.1 release the dependencies flip.

**Comment by jvliwanag** [comment]
Perhaps something like scalaz-stream versioning? 6.1 for scalaz-7.1, 6.1a for scalaz-7.2?

**Comment by seanparsons** [comment]
I'm amenable to that, let me create an appropriate series, if you're happy to redirect this PR?

**Comment by jvliwanag** [comment]
Sure!

**Comment by seanparsons** [comment]
I've created the 6.1a.x series for this, currently there are no differences between it and the 6.1.x series, including version numbers, until I sort all that stuff out later.

**Comment by jvliwanag** [comment]
Closing this in favor of #231

**Pull request closed without merging**
