### PR TITLE
Add support for decoding with validation.

### PR DESCRIPTION
**Pull request by kevinmeredith**
Closes https://github.com/argonaut-io/argonaut/issues/275.

### CODE REVIEW

**Comment by seanparsons** [comment]
That'll need to be in the argonaut-scalaz sub-project, which is why those tests have failed.

**Comment by kevinmeredith** [comment]
Could you please point me to the exact file into which I should add this method, @seanparsons?

Per the attached screen shot, I'm not sure where to add it:
screen shot 2017-07-06 at 8 06 23 am

Thanks!

**Comment by kevinmeredith** [comment]
Bump :)

**Comment by seanparsons** [comment]
So the likely location is in here: https://github.com/argonaut-io/argonaut/blob/master/argonaut-scalaz/shared/src/main/scala/argonaut/JsonScalaz.scala

You'd have to make an implicit wrapper for the `Json` datatype though so that the function could be invoked on instances of `Json`. Most of the `argonaut-scalaz` project itself is a bunch of typeclass instances.

**Comment by kevinmeredith** [comment]
Thanks, @seanparsons. I pushed up the a partial PR, i.e. no property-based test for the positive case.

When I tried to run the following, my command-line output just appeared to be paused for a few minutes, so I Control + C'd out of the terminal:

```
$sbt
>project argonaut-scalazJVM
>testOnly argonaut.JsonScalazSpecification
// paused for a few minutes before I exited out
```

Any idea why it would be so, apparently, slow to run the test? I have a new Macbook Pro, so hardware isn't an issue, I wouldn't expect.

**Comment by seanparsons** [comment]
@kevinmeredith No idea, I just did a clean and tried the same thing with `argonaut.JsonObjectScalazSpecification` and it ran in "normal for SBT" time for me.

I'd even expect it to be quite fast given that we use coursier to make the dependency downloading pretty quick.

**Comment by seanparsons** [comment]
Interestingly the Travis builds are failing with something about it taking way too long...

**Comment by seanparsons** [comment]
I'd surmise that one of those implicits in the test code is recursively calling itself or something along those lines

**Comment by kevinmeredith** [comment]
@seanparsons, thanks for taking a look! I removed the `Data.jsonNumber.suchThat(_ != null)`. Then, my tests ran successfully locally.

Please take a look at what I've added. I'm not too impressed by the property-based tests that I've added. Please give me feedback. Thanks!

**Pull request merged**
